import {hashSync} from 'bcrypt-ts-edge'

const sampleData = {
   users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: hashSync('123456',10),
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: hashSync('123456',10),
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    // ── Men's T-Shirts (4) ──
    {
      name: 'Nike Dri-FIT Cotton T-Shirt',
      slug: 'nike-dri-fit-cotton-t-shirt',
      category: "Men's T-Shirts",
      description: 'Sweat-wicking Dri-FIT technology with soft cotton comfort for everyday wear',
      images: [
        '/images/sample-products/nike-dri-fit-1.jpg',
        '/images/sample-products/nike-dri-fit-2.jpg',
      ],
      price: 35.00,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 23,
      stock: 15,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Adidas Essentials Crew T-Shirt',
      slug: 'adidas-essentials-crew-t-shirt',
      category: "Men's T-Shirts",
      description: 'Classic crew neck tee with iconic 3-stripe logo, made with recycled materials',
      images: [
        '/images/sample-products/adidas-essentials-1.jpg',
        '/images/sample-products/adidas-essentials-2.jpg',
      ],
      price: 29.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 31,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Under Armour Tech T-Shirt',
      slug: 'under-armour-tech-t-shirt',
      category: "Men's T-Shirts",
      description: 'UA Tech fabric is quick-drying, ultra-soft with anti-odor technology',
      images: [
        '/images/sample-products/ua-tech-1.jpg',
        '/images/sample-products/ua-tech-2.jpg',
      ],
      price: 32.50,
      brand: 'Under Armour',
      rating: 4.4,
      numReviews: 18,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Lacoste Classic Pique T-Shirt',
      slug: 'lacoste-classic-pique-t-shirt',
      category: "Men's T-Shirts",
      description: 'Timeless pique cotton petit piqué with embroidered crocodile branding',
      images: [
        '/images/sample-products/lacoste-pique-1.jpg',
        '/images/sample-products/lacoste-pique-2.jpg',
      ],
      price: 89.00,
      brand: 'Lacoste',
      rating: 4.7,
      numReviews: 42,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    // ── Men's Pants (4) ──
    {
      name: "Levi's 511 Slim Fit Jeans",
      slug: 'levis-511-slim-fit-jeans',
      category: "Men's Pants",
      description: 'Modern slim fit with slight taper, comfortable stretch denim for all-day wear',
      images: [
        '/images/sample-products/levis-511-1.jpg',
        '/images/sample-products/levis-511-2.jpg',
      ],
      price: 69.50,
      brand: "Levi's",
      rating: 4.5,
      numReviews: 56,
      stock: 14,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Dockers Classic Fit Khaki Pants',
      slug: 'dockers-classic-fit-khaki-pants',
      category: "Men's Pants",
      description: 'Timeless straight-leg khakis with wrinkle-resistant cotton twill finish',
      images: [
        '/images/sample-products/dockers-khaki-1.jpg',
        '/images/sample-products/dockers-khaki-2.jpg',
      ],
      price: 54.99,
      brand: 'Dockers',
      rating: 4.2,
      numReviews: 28,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Uniqlo Stretch Chino Pants',
      slug: 'uniqlo-stretch-chino-pants',
      category: "Men's Pants",
      description: 'Lightweight stretch chinos with a clean flat-front design and moisture-wicking finish',
      images: [
        '/images/sample-products/uniqlo-chino-1.jpg',
        '/images/sample-products/uniqlo-chino-2.jpg',
      ],
      price: 39.90,
      brand: 'Uniqlo',
      rating: 4.0,
      numReviews: 45,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'H&M Slim Fit Trousers',
      slug: 'hm-slim-fit-trousers',
      category: "Men's Pants",
      description: 'Tailored slim-fit trousers in stretch cotton with a modern cropped silhouette',
      images: [
        '/images/sample-products/hm-trousers-1.jpg',
        '/images/sample-products/hm-trousers-2.jpg',
      ],
      price: 34.99,
      brand: 'H&M',
      rating: 3.9,
      numReviews: 22,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    // ── Men's Jackets (4) ──
    {
      name: 'The North Face Windbreaker',
      slug: 'the-north-face-windbreaker',
      category: "Men's Jackets",
      description: 'WindWall wind-resistant shell with breathable mesh lining, packable into its own pocket',
      images: [
        '/images/sample-products/tnf-windbreaker-1.jpg',
        '/images/sample-products/tnf-windbreaker-2.jpg',
      ],
      price: 129.00,
      brand: 'The North Face',
      rating: 4.6,
      numReviews: 38,
      stock: 7,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Columbia Fleece Jacket',
      slug: 'columbia-fleece-jacket',
      category: "Men's Jackets",
      description: 'Plush thermal fleece with zippered pockets, ideal as a mid-layer or standalone piece',
      images: [
        '/images/sample-products/columbia-fleece-1.jpg',
        '/images/sample-products/columbia-fleece-2.jpg',
      ],
      price: 79.99,
      brand: 'Columbia',
      rating: 4.4,
      numReviews: 52,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Patagonia Nano Puff Jacket',
      slug: 'patagonia-nano-puff-jacket',
      category: "Men's Jackets",
      description: 'Lightweight insulated jacket with PrimaLoft Gold Eco, fair trade certified sewn',
      images: [
        '/images/sample-products/patagonia-nano-1.jpg',
        '/images/sample-products/patagonia-nano-2.jpg',
      ],
      price: 199.00,
      brand: 'Patagonia',
      rating: 4.8,
      numReviews: 27,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Arc'teryx Atom LT Hoodie",
      slug: 'arcteryx-atom-lt-hoodie',
      category: "Men's Jackets",
      description: 'Versatile synthetic insulated hoodie with Coreloft Compact insulation, wind-resistant shell',
      images: [
        '/images/sample-products/arcteryx-atom-1.jpg',
        '/images/sample-products/arcteryx-atom-2.jpg',
      ],
      price: 259.00,
      brand: "Arc'teryx",
      rating: 4.9,
      numReviews: 19,
      stock: 3,
      isFeatured: true,
      banner: null,
    },
    // ── Men's Shoes (4) ──
    {
      name: 'Nike Air Max 270',
      slug: 'nike-air-max-270',
      category: "Men's Shoes",
      description: 'Lifestyle sneaker with the largest Air unit yet, 270 degrees of visible Max Air cushioning',
      images: [
        '/images/sample-products/nike-airmax-1.jpg',
        '/images/sample-products/nike-airmax-2.jpg',
      ],
      price: 150.00,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 63,
      stock: 9,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Adidas Ultraboost',
      slug: 'adidas-ultraboost',
      category: "Men's Shoes",
      description: 'Responsive Boost midsole with Primeknit upper, designed for long-distance running comfort',
      images: [
        '/images/sample-products/adidas-ultraboost-1.jpg',
        '/images/sample-products/adidas-ultraboost-2.jpg',
      ],
      price: 180.00,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 71,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Clarks Leather Oxford Shoes',
      slug: 'clarks-leather-oxford-shoes',
      category: "Men's Shoes",
      description: 'Hand-stitched full-grain leather oxfords with cushioned insole and durable rubber outsole',
      images: [
        '/images/sample-products/clarks-oxford-1.jpg',
        '/images/sample-products/clarks-oxford-2.jpg',
      ],
      price: 120.00,
      brand: 'Clarks',
      rating: 4.3,
      numReviews: 34,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Timberland Classic Boots',
      slug: 'timberland-classic-boots',
      category: "Men's Shoes",
      description: 'Iconic 6-inch premium waterproof boots with seam-sealed construction and padded collar',
      images: [
        '/images/sample-products/timberland-boot-1.jpg',
        '/images/sample-products/timberland-boot-2.jpg',
      ],
      price: 198.00,
      brand: 'Timberland',
      rating: 4.5,
      numReviews: 48,
      stock: 5,
      isFeatured: false,
      banner: null,
    },
    // ── Men's Accessories (2) ──
    {
      name: 'Fossil Leather Belt',
      slug: 'fossil-leather-belt',
      category: "Men's Accessories",
      description: 'Genuine leather dress belt with brushed nickel buckle, 35mm width',
      images: [
        '/images/sample-products/fossil-belt-1.jpg',
        '/images/sample-products/fossil-belt-2.jpg',
      ],
      price: 45.00,
      brand: 'Fossil',
      rating: 4.1,
      numReviews: 15,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Ray-Ban Aviator Sunglasses',
      slug: 'ray-ban-aviator-sunglasses',
      category: "Men's Accessories",
      description: 'Legendary teardrop-shaped aviators with gold-tone frame and G-15 polarized lenses',
      images: [
        '/images/sample-products/rayban-aviator-1.jpg',
        '/images/sample-products/rayban-aviator-2.jpg',
      ],
      price: 163.00,
      brand: 'Ray-Ban',
      rating: 4.8,
      numReviews: 82,
      stock: 4,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
